name: Scala and Java build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
      
jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        include:
          - spark: 3.3.0
            scala: 2.13.8
            jackson: 2.13.3
            jdk: '8'
            skipTests: ''
          - spark: 3.3.0
            scala: 2.12.15
            jackson: 2.13.3
            jdk: '8'
            skipTests: ''            
          - spark: 3.3.0
            scala: 2.12.15
            jackson: 2.13.3
            jdk: '11'
            skipTests: '-DskipTests'            
          - spark: 3.2.0
            scala: 2.12.15
            jackson: 2.12.3
            jdk: '8'
            skipTests: ''            
          - spark: 3.1.2
            scala: 2.12.15
            jackson: 2.10.0
            jdk: '8'
            skipTests: ''            
          - spark: 3.0.3
            scala: 2.12.15
            jackson: 2.10.0
            jdk: '8'
            skipTests: ''

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - run: git submodule update --init --recursive # Checkout Git submodule if necessary
    - env:
        SPARK_VERSION: ${{ matrix.spark }}
        SCALA_VERSION: ${{ matrix.scala }}
        JACKSON_VERSION: ${{ matrix.jackson }}
        SKIP_TESTS: ${{ matrix.skipTests}}
      run: mvn -q clean install -Dscala=${SCALA_VERSION:0:4} -Dspark.version=${SPARK_VERSION} -Dsedona.jackson.version=${JACKSON_VERSION} ${SKIP_TESTS}
    - run: mkdir staging
    - run: cp core/target/sedona-*.jar staging
    - run: cp sql/target/sedona-*.jar staging
    - run: cp viz/target/sedona-*.jar staging
    - run: cp python-adapter/target/sedona-*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: generated-jars
        path: staging
